<a href="https://colab.research.google.com/github/Pushyanth-sai/LMS-AD/blob/main/12_02_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import pandas as pd
data = pd.read_csv("/content/fake_news.csv", on_bad_lines='skip', quoting=3)
data.head()

id  \
0                                              House Dem Aide: We Didn’t Even See Comey’s Lett...                                      Darrell Lucus   
With apologies to Keith Olbermann               there is no doubt who the Worst Person in The ...   it looks like we also know who the second-wor...   
As we now know                                  Comey notified the Republican chairmen and Dem...                                          Judiciary   
— Jason Chaffetz (@jasoninthehouse) October 28  2016                                                                                             NaN   
Of course                                       we now know that this was not the case . Comey...   and possibly an entire term’s worth of them. ...   

                                                                                                                                               title  \
0                                              House Dem Aide: We Didn’t Even See Comey’s Lett...  "House Dem Aide: We Didn’t Even See Comey’s Le...   
With apologies to Keith Olbermann               there is no doubt who the Worst Person in The ...   the ranking Democrats on the relevant committ...   
As we now know                                  Comey notified the Republican chairmen and Dem...   and Oversight committees that his agency was ...   
— Jason Chaffetz (@jasoninthehouse) October 28  2016                                                                                             NaN   
Of course                                       we now know that this was not the case . Comey...                                                NaN   

                                                                                                                                              author  \
0                                              House Dem Aide: We Didn’t Even See Comey’s Lett...   2016 Subscribe Jason Chaffetz on the stump in...   
With apologies to Keith Olbermann               there is no doubt who the Worst Person in The ...                                                NaN   
As we now know                                  Comey notified the Republican chairmen and Dem...   Oversight Committee Chairman Jason Chaffetz s...   
— Jason Chaffetz (@jasoninthehouse) October 28  2016                                                                                             NaN   
Of course                                       we now know that this was not the case . Comey...                                                NaN   

                                                                                                                                                text  \
0                                              House Dem Aide: We Didn’t Even See Comey’s Lett...               Utah ( image courtesy Michael Jolley   
With apologies to Keith Olbermann               there is no doubt who the Worst Person in The ...                                                NaN   
As we now know                                  Comey notified the Republican chairmen and Dem...   ""The FBI has learned of the existence of ema...   
— Jason Chaffetz (@jasoninthehouse) October 28  2016                                                                                             NaN   
Of course                                       we now know that this was not the case . Comey...                                                NaN   

                                                                                                                                              label  
0                                              House Dem Aide: We Didn’t Even See Comey’s Lett...   available under a Creative Commons-BY license)   
With apologies to Keith Olbermann               there is no doubt who the Worst Person in The ...                                               NaN  
As we now know                              

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5402 entries, ('0', 'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It') to ('She said: “The streets are littered with rubbish and faeces. We can hear blood-curdling screams coming from the camp in the middle of the night."', '1')
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      2698 non-null   object
 1   title   1864 non-null   object
 2   author  1105 non-null   object
 3   text    583 non-null    object
 4   label   212 non-null    object
dtypes: object(5)
memory usage: 557.4+ KB


In [4]:
data.isna().sum()

id        2704
title     3538
author    4297
text      4819
label     5190
dtype: int64

In [5]:
data = data.drop(['id'], axis=1)

In [6]:
data = data.fillna('')

In [7]:
data['content'] = data['author']+' '+data['title']+' '+data['text']

In [8]:
data = data.drop(['title','author','text'], axis=1)

In [9]:
data.head()

label  \
0                                              House Dem Aide: We Didn’t Even See Comey’s Lett...   available under a Creative Commons-BY license)    
With apologies to Keith Olbermann               there is no doubt who the Worst Person in The ...                                                     
As we now know                                  Comey notified the Republican chairmen and Dem...                                                     
— Jason Chaffetz (@jasoninthehouse) October 28  2016                                                                                                  
Of course                                       we now know that this was not the case . Comey...                                                     

                                                                                                                                             content  
0                                              House Dem Aide: We Didn’t Even See Comey’s Lett...   2016 Subscribe Jason Chaffetz on the stump in...  
With apologies to Keith Olbermann               there is no doubt who the Worst Person in The ...    the ranking Democrats on the relevant commit...  
As we now know                                  Comey notified the Republican chairmen and Dem...   Oversight Committee Chairman Jason Chaffetz s...  
— Jason Chaffetz (@jasoninthehouse) October 28  2016                                                                                                  
Of course                                       we now know that this was not the case . Comey...

In [10]:
data['content'] = data['content'].apply(lambda x: " ".join(x.lower() for x in x.split()))

In [11]:
data['content'] = data['content'].str.replace('[^\w\s]','')

In [12]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [13]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
data['content'] = data['content'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

In [14]:
!pip install textblob

In [15]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [16]:
# Do lemmatization
from nltk.stem import WordNetLemmatizer
from textblob import Word
data['content'] = data['content'].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))
data['content'].head()

0                                               House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It                                                                                                                                                                                                                                                                                                                    2016 subscribe jason chaffetz stump american f...
With apologies to Keith Olbermann                there is no doubt who the Worst Person in The World is this week–FBI Director James Comey. But according to a House Democratic aide                                                                                                                                                                                                                                                                 ranking democrat relevant committee didn’t hea...
As we now know                                   Comey notified the Republican chairmen and Democratic ranking members of the House Intelligence                                                                                                                                                                                                                                                                                                     oversight committee chairman jason chaffetz se...
— Jason Chaffetz (@jasoninthehouse) October 28   2016                                                                                                                                                                                                                                                                                                                                                                                                                                                 
Of course                                        we now know that this was not the case . Comey was actually saying that it was reviewing the emails in light of “an unrelated case”–which we now know to be Anthony Weiner’s sexting with a teenager. But apparently such little things as facts didn’t matter to Chaffetz. The Utah Republican had already vowed to initiate a raft of investigations if Hillary wins–at least two years’ worth                                                     
Name: content, dtype: object

In [17]:
#separating the data and label
X = data[['content']]
y = data['label']

In [18]:
from sklearn.model_selection import train_test_split

In [39]:
# Check for classes with only one sample
class_counts = data['label'].value_counts()
rare_classes = class_counts[class_counts == 1].index.tolist()

# Print rare classes
if rare_classes:
    print("Classes with only one sample:", rare_classes)

# Option 1: Remove rare classes from the dataset
# If you have a large dataset and removing a few samples won't significantly affect your results,
# you can remove the samples belonging to rare classes.
if rare_classes:
    data = data[~data['label'].isin(rare_classes)]
# Option 2: Oversample rare classes
# If removing rare classes is not desirable, you can oversample them to increase their representation
# in the dataset. This can be done using techniques like SMOTE (Synthetic Minority Over-sampling Technique).
# !pip install imbalanced-learn
# from imblearn.over_sampling import SMOTE
# smote = SMOTE(random_state=45)
# X_resampled, y_resampled = smote.fit_resample(X, y)

# Option 3: Adjust 'stratify' parameter
# If you don't want to remove or oversample rare classes, you can remove the 'stratify' parameter
# from train_test_split. This will result in a random split, and the class proportions might not be
# maintained in the training and test sets.

# Proceed with train_

In [31]:
#validate the shape of train and test dataset
print (X_train.shape)
print (y_train.shape)
print (X_test.shape)
print (y_test.shape)

(3781, 1)
(3781,)
(1621, 1)
(1621,)


In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [33]:
tfidf_vect = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', max_features=5000)
tfidf_vect.fit(data['content'])
xtrain_tfidf = tfidf_vect.transform(X_train['content'])
xtest_tfidf = tfidf_vect.transform(X_test['content'])

In [37]:
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn import metrics
pclf = PassiveAggressiveClassifier()
pclf.fit(xtrain_tfidf, y_train)
predictions = pclf.predict(xtest_tfidf)
print(metrics.classification_report(y_test, predictions))





                                                                                                                                                                                                                                                                                                                                                                     precision    recall  f1-score   support

                                                                                                                                                                                                                                                                                                                                                                          0.96      1.00      0.98      1558
                                                                                                                                                                                                             

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [41]:
tfidf_vect = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', max_features=5000)
tfidf_vect.fit(data['content'])
xtrain_tfidf = tfidf_vect.transform(X_train['content'])
xtest_tfidf = tfidf_vect.transform(X_test['content'])

In [42]:
print(metrics.confusion_matrix(y_test,predictions))

[[1553    0    0 ...    1    0    0]
 [   1    0    0 ...    0    0    0]
 [   1    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   1    0    0 ...    0    0    0]
 [   7    0    0 ...    0    0    0]]


In [44]:
from sklearn.neural_network import MLPClassifier
mlpclf = MLPClassifier(hidden_layer_sizes=(256,64,16),
                       activation = 'relu',
                       solver = 'adam')
mlpclf.fit(xtrain_tfidf, y_train)
predictions = mlpclf.predict(xtest_tfidf)
print(metrics.classification_report(y_test, predictions))

                                                                                                                                                                                                                                                                                                                                                                     precision    recall  f1-score   support

                                                                                                                                                                                                                                                                                                                                                                          0.97      0.97      0.97      1558
                                                                                                                                                                                                             

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_

In [45]:
print(metrics.confusion_matrix(y_test,predictions))

[[1518    0    0 ...    0    1    1]
 [   1    0    0 ...    0    0    0]
 [   1    0    0 ...    0    0    0]
 ...
 [   1    0    0 ...    0    0    0]
 [   7    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]


In [46]:
import pickle
# Save trained model to file
pickle.dump(mlpclf, open("fakenews1.pkl", "wb"))